In [21]:
#DEPENDENCIES
import os
import pandas as pd
import random

bookDataLocation = "resources/books.csv"

In [22]:
df = pd.read_csv(bookDataLocation)

df.head(10)

,bookID,title,authors,average_rating,isbn,isbn13,language_code,# num_pages,ratings_count,text_reviews_count
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling-Mary GrandPré,4.56,439785960,9.780440e+12,eng,652,1944099,26249
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling-Mary GrandPré,4.49,439358078,9.780440e+12,eng,870,1996446,27613
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling-Mary GrandPré,4.47,439554934,9.780440e+12,eng,320,5629932,70390
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.41,439554896,9.780440e+12,eng,352,6267,272
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling-Mary GrandPré,4.55,043965548X,9.780440e+12,eng,435,2149872,33964
5,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling-Mary GrandPré,4.78,439682584,9.780440e+12,eng,2690,38872,154
6,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.69,976540606,9.780980e+12,en-US,152,18,1
7,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,439827604,9.780440e+12,eng,3342,27410,820
8,12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,517226952,9.780520e+12,eng,815,3602,258
9,13,The Ultimate Hitchhiker's Guide to the Galaxy,Douglas Adams,4.38,345453743,9.780350e+12,eng,815,240189,3954

In [27]:
ISBN_list = pd.DataFrame(columns=["title", "authors", "isbn"])

for x in range(100):
    randomBook = random.randint(1,10000)
    book = df.loc[df["bookID"] == randomBook, ["title", "authors", "isbn"]]
    ISBN_list = ISBN_list.append(book)
    
ISBN_list.head()

,title,authors,isbn
1608,1421: The Year China Discovered America,Gavin Menzies,006054094X
1908,The Creation of the American Republic 1776-1787,Gordon S. Wood,807847232
3050,Embroideries,Marjane Satrapi-Anjali Singh,375714677
422,The Clan of the Cave Bear Part 2 of 2 (Earth'...,Jean M. Auel,5557075313
112,A Wrinkle in Time: With Related Readings (A Wr...,Madeleine L'Engle,821925326